inheritedBy:
  files:
    - 'go.mod'

tasks:
  platform-cli-path:
    env:
      GOOS: 'darwin'
      GOARCH: 'arm64'
      CLI_PLATFORM_PACKAGE: 'maratus-cli-darwin-arm64'
      CLI_BINARY_NAME: 'maratus'
    outputs:
      - '/packages/${CLI_PLATFORM_PACKAGE}/bin/${CLI_BINARY_NAME}'
