fileGroups:
  repo-config:
    - '/repo.yml'
  components-source:
    - '/components/*/src/**/*'
    - '/components/*/package.json'
  registry-meta:
    - '/registry/*/package.json'
    - '/registry/*/meta.json'
  codemod-meta:
    - '/codemods/*/package.json'
    - '/codemods/*/meta.json'
