fileGroups:
  repo-config:
    - '/repo.yml'
  registry-meta:
    - '/registry/*/package.json'
    - '/registry/*/meta.json'
  codemod-meta:
    - '/codemods/*/package.json'
    - '/codemods/*/meta.json'
