name: _Test Unit

on:
  workflow_call:
    inputs:
      base-sha:
        required: true
        type: string
      head-sha:
        required: true
        type: string

jobs:
  test-unit:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
      - name: Check out repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Set up Moon toolchain
        uses: moonrepo/setup-toolchain@v0
        with:
          auto-install: true
          auto-setup: true

      - name: Run affected unit tests
        run: |
          moon ci :test-unit \
            --base "${{ inputs.base-sha }}" \
            --head "${{ inputs.head-sha }}" \
            --include-relations
